### ISSUE TITLE
Not able to install build-essential - debian_buster_var02

### ISSUE THREAD

**Issue by berkutta** [varigit/debian-var#14]
When trying to install the build-essential package or gcc package I'm getting dependency issues. Is there a solution for this? I already tried to disable the local apt repo + testing + backports repo but still dependency problems.

```
root@imx8mm-var-dart:~# apt install build-essential
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 build-essential : Depends: gcc (>= 4:8.3) but it is not going to be installed
                   Depends: g++ (>= 4:8.3) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by leoniloris** [comment]
There are a bunch of broken packages shipped along with this debian rootfs.

What I did instead was to try to use `aptitude`, and select an option that does not totally remove `libc6` or `libcrypt` (you risk bricking the board and ending up having to install the debian again).

``` bash
$ apt install -y aptitude
...
$ aptitude install build-essential
```

**Comment by hj2006** [comment]
Due to GPU library dependencies for Weston display, we had to upgrade the (libc6 >=2.29), which was only available on bullseye under the testing phase from debian.

Please run
apt-get install build-essential/testing gcc/testing g++/testing
It should install the proper version for your building,

Anything related to the building source code (automake, cmake, gcc, g++ etc) please use

apt-get -y install **package/testing** this should install the proper version of the package.

Please log your ticket to https://varisciteportal.axosoft.com/ for future all your questions and concerns

We are currently working on Debian Bullseye and this issue will be fixed in the upcoming Debian builds.

**Comment by berkutta** [comment]
Great, thanks!
